### ISSUE TITLE
Add server to public server list

### ISSUE THREAD

**Issue by ooonea** [jedisct1/dnscrypt-server-docker#13]
Hi,
I created a new server using scaleway and driving this project. The server is therefore a non-censoring, non-logging, DNSSEC-capable, DNSCrypt-enabled DNS resolver. Can you add it to the public server list? Maintained by lucenera with Scaleway server in France.
I followed the guide slavishly, because I do not understand anything about the docker and all that DNS wandering. I have only superficial knowledge. However, I use Linux (Arch Linux, Ubuntu and OpenWRT).
I hope I did well. However the server is tested and works.
I understand that it does not support DNS over HTTPS? Can this function be implemented?

**Comment by jedisct1** [comment]
Hi!

And thanks for running this server!

Yes, it can be added to the public list. What name would you want for it? What is its DNS stamp?
That's pretty much all I need to add it :)

You are correct, this Docker image doesn't support DNS over HTTPS since DNSCrypt is faster and generally more reliable, but this is definitely something that may be added in a future version.

**Comment by ooonea** [comment]
I wish the name was `suami`. DNS stamp is `sdns://AQcAAAAAAAAAETUxLjE1OC43MC4xNTk6NDQzIIwP1sE7UXuXPsWPLGHCvvdSuthA7MIsMQ09yO4bVnZjGTIuZG5zY3J5cHQtY2VydC5zdWFtaS5jb20`

Could you suggest where to find useful guides on docker and what's in your container?

Thank you for your wonderful work.

**Comment by jedisct1** [comment]
Welcome to `suami`! You've just been added to the list.

I'm using it right now and it works well! Thanks for running this server!

The scripts present in the container, as well as everything used to build the image are in [this repository](https://github.com/jedisct1/dnscrypt-server-docker), the very same one you opened a ticket in :)

Here is the `Dockerfile` with all the commands that were executed in order to create the image for the container running your DNS server: https://github.com/jedisct1/dnscrypt-server-docker/blob/master/Dockerfile

To learn more about docker, this is a nice guide: https://docker-curriculum.com/
