### ISSUE TITLE
Flesh out doco

### ISSUE THREAD

**Issue by shleeable** [jedisct1/dnscrypt-server-docker#3]
Hey,

I've got a bunch of questions regarding the unmentioned parts... 

if the SDNS string contains the ip and port, public key and a FQDN..... 

Do I need to do anything with the public key?
what do I need with the FQDN? 2.dnscrypt-cert.blah.what
Do I need to setup an A record for that address to the server?
and 
Reverse DNS? Do I need to get the ReverseDNS pointed to blah.what or the full FQDN?

Can I change the default port from 443 to 8443 and just update the SDNS if I wanted to host my webpage on 443?

**Comment by mibere** [comment]
Hi,

> Do I need to do anything with the public key?
> what do I need with the FQDN? 2.dnscrypt-cert.blah.what

As DNSCrypt server operator you don't get in touch with the public key and FQDN.
You don't have to enter it in any file.

> Do I need to setup an A record for that address to the server?

No, a static IP is sufficient. No need for a A or CNAME DNS record. At least I'm not aware of.

> Reverse DNS? Do I need to get the ReverseDNS pointed to blah.what or the full FQDN?

No, you can use whatever as rDNS.

> Can I change the default port from 443 to 8443 and just update the SDNS if I wanted to host my webpage on 443?

Yes - additionally you also have to change the settings of or in the running container, if you already have one.
But, it's better to choose 443 as port for a public DNSCrypt server, because there are users behind (company) firewalls. Port 443 is open in most cases (for HTTPS), but not 8443.
I'm running a public DNSCrypt server on port 443, and the [website](http://dnscrypt.me/) at port 80 and for TLS on 8443.

By the way, post issues and questions [here](https://github.com/DNSCrypt/dnscrypt-server-docker/issues).

**Comment by jedisct1** [comment]
What he said :)
